### ISSUE TITLE
ReleaseBundle doesn't work for HEAD out of the box.

### ISSUE THREAD

**Issue by Pokute** [ReactWindows/react-native-windows#830] opened 2016-10-26 14:02 UTC
When running a project after following steps:

```
react-native init projectname
cd projectname
npm install --save-dev rnpm-plugin-windows
react-native windows  --windowsVersion ReactWindows/react-native-windows
Open the Solution in projectname\windows
Build and run a ReleaseBundle
```

I get an exception thrown in when I start the project from Visual Studio 2015 in ReleaseBundle (target platform doesn't matter.)
This happens regardless whether I actually create a bundle beforehand or not.

This is actually fixed by compiling and running the Release build first. Then after packaging the bundle, ReleaseBundle works all right.

**Comment by rozele** [comment] 2016-10-26 16:10
@Pokute I am not able to reproduce this issue.  If the bundle is not generated then the app will crash (because it throws an exception letting you know that the bundle has not been generated).

If I generate the bundle, then build the project, and then run, everything works as expected.

If you don't build the project after generating the bundle, it will continue to fail with a missing bundle.  This is because there is a step in the build process to copy the bundle into the correct location in the Appx package.

**Comment by Pokute** [comment] 2016-10-26 18:44
That's a different exception if it can't find the bundle. This one is somewhere deep in system libraries.

**Comment by rozele** [comment] 2016-10-26 18:46
unfortunately I can't repro from a blank app, is there some other change you made to the default app?

**Comment by Pokute** [comment] 2016-10-26 19:40
Could repro on my home computer (though only after switching target platform once, installing all the SDKs and nugets might've skipped over the problem.)

**Comment by Pokute** [comment] 2016-10-26 20:00
Ok, I can't reproduce it on my home computer...

**Comment by rozele** [comment] 2016-10-27 12:57
@Pokute can I close this, or would you like to keep trying for a repro?

**Comment by rozele** [comment] 2016-10-31 13:16
Closing, please reopen if you get a consistent repro

**Closed by rozele** 2016-10-31 13:16 UTC

**Comment by Pokute** [comment] 2016-11-02 14:49
Yeah, couldn't replicate it either now on work comp.

You could try to look why release exceptions are caught and rethrown as cryptic library-specific exceptions with useless data instead of original messages.
