### ISSUE TITLE
Crashes using simple NPM packages

### ISSUE THREAD

**Issue by andrewwebber** [ReactWindows/react-native-windows#617] opened 2016-08-23 16:40 UTC
It seems confusing to have contrasting behavior for simple projects that use external NPM packages. 

In the example below we have downloaded the 'uuid' package from NPM and attempt to create a new guid to display on the screen.

```javascript
var uuid = require('uuid');

class rnwindows extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          {uuid.v4()}
        </Text>        
      </View>
    );
  }
}
```

On iOS (and Android) the expected result is delivered.
![iOS](https://github.com/andrewwebber/rnwindows/raw/master/docs/ios.png)

On Windows we get a crash as an unknown module is used. 
![iOS](https://github.com/andrewwebber/rnwindows/raw/master/docs/windows.PNG)

I have created a full example repro [here](https://github.com/andrewwebber/rnwindows)

**Comment by rozele** [comment] 2016-08-24 16:05
This is because the "crypto" module is not available for Chakra, we may need to polyfill it...

**Comment by rozele** [comment] 2016-08-24 16:19
@andrewwebber Are you running on a device or running through a remote debugger for iOS and Android?

**Comment by andrewwebber** [comment] 2016-08-24 16:23
@rozele I run on the device as I am porting a camera bar-code reader app

**Comment by rozele** [comment] 2016-08-24 16:26
Thanks @andrewwebber I guess we're not picking up the browser version of the uuid module. (credit: @brentvatne)

**Comment by andrewwebber** [comment] 2016-08-24 16:29
I was interesting trying to write a work around with a native module as they are asynchronous 

**Warning dirty hack :)**
```c#
public class UUIDGeneratorModule : ReactContextNativeModuleBase
    {
        public UUIDGeneratorModule(ReactContext reactContext) : base(reactContext)
        {            
        }

        public override string Name
        {
            get
            {
                return "UUIDGenerator";
            }
        }

        [ReactMethod]
        public void newID(JObject config, ICallback actionCallback)
        {
            var uuid = Guid.NewGuid().ToString();
            actionCallback.Invoke(uuid);
        }
    }
```

```javascript
/* jshint esnext: true */
import { NativeModules } from 'react-native';
var UUIDGenerator = NativeModules.UUIDGenerator;
var next = "";
UUIDGenerator.newID({}, (result)=>{
  next = result;
})

function newID(callback){
  UUIDGenerator.newID({}, (result)=>{
    next = result;
    console.error(result);
  })

  return next;
};

export {newID};

```

**Comment by rozele** [comment] 2016-08-24 16:34
That's certainly one way to do it, but generally we need to fix the bug that's preventing Windows from picking up the browser versions of the NPM packages.

**Comment by andrewwebber** [comment] 2016-08-24 16:37
@rozele with that one exception all my other NPM packages ported smoothly

```json
"dependencies": {
    "hi-base32": "^0.1.1",
    "otplib": "^3.0.1",
    "react": "15.2.1",
    "react-native": "^0.31.0",
    "react-native-barcodescanner": "^3.1.1",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-swipe-list-view": "^0.2.3",
    "react-native-windows": "^0.31.3",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-actions": "^0.10.1",
    "redux-thunk": "^2.1.0",
    "shitty-qs": "^1.0.1",
    "uri-js": "^2.1.1",
    "uuid": "^2.0.2",
    "window-size": "^0.2.0"
  },
```

**Comment by rozele** [comment] 2016-08-24 16:38
@andrewwebber this is actually a bug in the react-native packager running on Windows.  If you run your same example on an Android emulator on Windows, you'll get the same exception regarding the missing 'crypto' module.

**Comment by andrewwebber** [comment] 2016-08-24 16:47
@rozele  I "dual boot" a Macbook Pro into three partitions and develop Android (emulator) on fedora. I am checking now on the Fedora to exclude this being a Windows emulator issue...

**Comment by andrewwebber** [comment] 2016-08-24 17:31
![fedora](https://cloud.githubusercontent.com/assets/6299645/17940887/5a2e60ac-6a31-11e6-8e11-95001b0e4ccc.png)

@rozele Android Emulator on Fedora

**Comment by rozele** [comment] 2016-08-24 18:06
@andrewwebber we suspect this is a path issue. the problem is both for react-native-windows and ReactAndroid apps when running on Windows.

**Comment by rozele** [comment] 2016-08-24 19:53
@andrewwebber you can fix the issue by editing the behavior of node-haste as in this PR https://github.com/facebook/react-native/pull/9572.  

In your example, you're using react-native@0.31.0, so node-haste is still a separate dependency.  You should still be able to find the Package.js file in that node module folder.

**Comment by andrewwebber** [comment] 2016-08-24 20:02
@rozele thanks for taking the time to submit the issue and merge request. I will test your changes, thanks!

Once again great project - my next task is the wrap the [UWPCommunityToolkit](https://github.com/Microsoft/UWPCommunityToolkit) in react native :)

**Comment by rozele** [comment] 2016-08-24 21:27
Closing, we'll have to wait on https://github.com/facebook/react-native/pull/9572, please re-open if this change does not solve your issue.

**Closed** 2016-08-24 21:27 UTC
