### ISSUE TITLE
Embedding React Native within existing UWP app

### ISSUE THREAD

**Issue by globeport** [ReactWindows/react-native-windows#828] opened 2016-10-26 08:47 UTC
Is it possible to add React Native to an existing windows app? And if so, is it possible to embed multiple react native views?

Thanks,
Stuart

**Comment by rozele** [comment] 2016-10-26 13:38
@globeport This should be possible.  You don't have to embed React Native as a ReactPage, but you can actually just place a root view anywhere in your app and go from there.  Embedding multiple views might be trickier, but do-able in theory.  It's questionable whether you need a separate JavaScript runtime per view (which would be too much overhead I assume).  Unfortunately, we don't have any docs for this yet (there's a pending doc [here](https://github.com/ReactWindows/react-native-windows/blob/master/docs/EmbeddedAppWindows.md), but nothing in it, sorry!)

**Comment by rozele** [comment] 2016-10-27 12:58
I'm going to close this as a dupe of #451.

**Closed by rozele** 2016-10-27 12:58 UTC
Labels: duplicate

**Comment by globeport** [comment] 2016-10-27 13:55
Thanks, @rozele good in the first instance to know that its possible.
