### ISSUE TITLE
Updated  – can't run project

### ISSUE THREAD

**Issue by Petter-W** [ReactWindows/react-native-windows#818] opened 2016-10-24 07:11 UTC
I've update my project to 0.35.0, v0.36.0-rc.0 and 2ca912488695b5740f0d052548fc36b80666f98a, but the project crashes. It seems to happen when I run local modules.
The last thing it logs is `Exception thrown: 'System.InvalidOperationException' in ReactNative.dll`. If I press continue in Visual Studio the app displays `Unexpected Batch Response` in the view.

<img width="328" alt="windows_10__running_" src="https://cloud.githubusercontent.com/assets/2606287/19636458/b78bd636-99c9-11e6-9b9f-aae8b1165785.png">

Any ideas what this could be?

**Comment by Petter-W** [comment] 2016-10-24 08:15
Using `react-native run-windows` in the terminal gives the the following errors:
```
PS C:\Users\user\developer\projectName> react-native run-windows
Restoring NuGet packages
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Restoring packages for C:\Users\user\developer\projectName\windows\projectName\project.json...
Restoring packages for C:\Users\user\developer\projectName\node_modules\react-native-windows\ReactWindows\ReactNative\proj
ect.json...
Committing restore...
C:\Users\user\developer\projectName\node_modules\react-native-windows\ReactWindows\ReactNative\ReactNative.csproj
Restore completed in 1977ms.
Committing restore...
C:\Users\user\developer\projectName\windows\projectName\projectName.csproj
Restore completed in 2101ms.

NuGet Config files used:
    C:\Users\user\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json

Building C:/Users/user/developer/projectName/windows/projectName.sln
ERROR: The system was unable to find the specified registry key or value.
Found MSBuild v14.0 at C:\Program Files (x86)\MSBuild\14.0\bin
ERROR: The system was unable to find the specified registry key or value.
Found MSBuild v4.0 at C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
Building Solution: C:/Users/user/developer/projectName/windows/projectName.sln
Build configuration: Debug
Build platform: x86
Build failed with message Error: Command failed: "C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe" "C:/Users/user/d
eveloper/projectName/windows/projectName.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal /nologo /p:Configuration=
Debug /p:Platform=x86
. Check your build configuration.
```

**Comment by henningms** [comment] 2016-10-24 10:27
I can further elaborate on this issue for the particular solution Petter-W is working on:

The issue we're experiencing is that React Native is not able to invoke the method we're trying to access from Javascript. It has worked fine in earlier versions of RN, but now we have an issue. 

It's hard for us to debug what is exactly happening because it's happening in React Native itself. 

The method signature: public void encodeBytes(object input, IPromise promise) -- where input is either a JArray or JObject.

**Comment by rozele** [comment] 2016-10-24 13:19
@Petter-W which version of react-native and which version of react-native-windows?

**Comment by Petter-W** [comment] 2016-10-24 13:55
I've tried various combinations of react-native and of react-native-windows. 0.35.0 and v0.36.0-rc.0. I run the same versions on react-native and of react-native-windows (e.g. 0.35.0 on both).

**Comment by rozele** [comment] 2016-10-24 14:08
Is this also an issue when running 0.35.0 for both?

**Comment by Petter-W** [comment] 2016-10-24 14:09
Yes.

**Comment by rozele** [comment] 2016-10-24 14:17
Can you set a break point at https://github.com/ReactWindows/react-native-windows/blob/master/ReactWindows/ReactNative/Bridge/ReactBridge.cs#L120
```
            if (moduleIds == null || methodIds == null || paramsArray == null ||
                moduleIds.Length != methodIds.Length || moduleIds.Length != paramsArray.Count)
            {
                throw new InvalidOperationException("Unexpected React batch response.");
            }
```

And see why this exception is being thrown?  It would be great if you could copy the contents of the `response` payload.

**Comment by rozele** [comment] 2016-10-24 14:23
I suspect some assumptions have changed with the native bridge, I'm digging into this method:
https://github.com/facebook/react-native/blob/cfae3e376d96653e5ad48e0d0398674a954d3637/ReactCommon/cxxreact/MethodCall.cpp#L16

to make sure I'm not missing something.

**Comment by henningms** [comment] 2016-10-24 15:12
This is the response object: {[ [21], [1], [], 436 ]} so it is failing on the moduleIds.Length != paramsArray.Count I guess.

This is the object we're trying to pass in:
{"0":24,"1":84,"2":14,"3":64,"4":105,"5":213,"6":86,"7":233,"8":215,"9":209,"10":72,"11":124,"12":153,"13":7,"14":235,"15":206,"16":169,"17":38,"18":33,"19":149,"20":213,"21":126,"22":130,"23":148,"24":178,"25":60,"26":139,"27":20,"28":195,"29":229,"30":228,"31":87,"32":222,"33":139,"34":251,"35":202,"36":249,"37":226,"38":60,"39":150,"40":66,"41":22,"42":89,"43":110,"44":97,"45":229,"46":80,"47":175,"48":102,"49":182,"50":113,"51":216,"52":59,"53":232,"54":89,"55":204,"56":123,"57":213,"58":37,"59":136,"60":124,"61":73,"62":70,"63":62,"64":97,"65":217,"66":162,"67":225,"68":234,"69":135,"70":154,"71":91,"72":225,"73":93,"74":98,"75":114,"76":250,"77":244,"78":19,"79":161,"80":30,"81":151,"82":230,"83":218,"84":99,"85":152,"86":11,"87":192,"88":124,"89":248,"90":19,"91":169,"92":120,"93":186,"94":42,"95":240,"96":60,"97":173,"98":38,"99":254,"100":77,"101":81,"102":66,"103":220,"104":91,"105":85,"106":213,"107":168,"108":136,"109":204,"110":183,"111":44,"112":86,"113":155,"114":149,"115":222,"116":41,"117":202,"118":90,"119":215,"120":82,"121":83,"122":239,"123":73,"124":211,"125":149,"126":52,"127":51,"128":133,"129":123,"130":3,"131":233,"132":74,"133":183,"134":148,"135":107,"136":221,"137":184,"138":251,"139":160,"140":72,"141":127,"142":28,"143":48,"144":64,"145":107,"146":188,"147":47,"148":62,"149":53,"150":137,"151":105,"152":249,"153":160,"154":237,"155":139,"156":181,"157":115,"158":11,"159":11,"160":208,"161":195,"162":86,"163":211,"164":83,"165":135,"166":223,"167":160,"168":109,"169":175,"170":212,"171":120,"172":139,"173":39,"174":8,"175":227,"176":182,"177":180,"178":119,"179":91,"180":0,"181":191,"182":179,"183":130,"184":78,"185":99,"186":122,"187":60,"188":24,"189":193,"190":97,"191":167,"192":96,"193":149,"194":208,"195":219,"196":153,"197":16,"198":250,"199":50,"200":32,"201":145,"202":177,"203":93,"204":12,"205":32,"206":131,"207":95,"208":129,"209":164,"210":196,"211":42,"212":163,"213":241,"214":196,"215":36,"216":204,"217":238,"218":243,"219":41,"220":96,"221":165,"222":32,"223":113,"224":246,"225":0,"226":215,"227":45,"228":188,"229":141,"230":115,"231":36,"232":157,"233":44,"234":235,"235":224,"236":16,"237":233,"238":200,"239":216,"240":118,"241":160,"242":220,"243":130,"244":24,"245":87,"246":100,"247":59,"248":232,"249":236,"250":206,"251":176,"252":242,"253":179,"254":196,"255":238,"256":66,"257":161,"258":39,"259":248,"260":8,"261":208,"262":232,"263":173,"264":105,"265":254,"266":205,"267":254,"268":171,"269":159,"270":139,"271":15,"272":100,"273":179,"274":14,"275":253,"276":209,"277":80,"278":97,"279":194,"280":26,"281":222,"282":194,"283":65,"284":181,"285":220,"286":66,"287":34,"288":138,"289":247,"290":200,"291":129,"292":48,"293":220,"294":197,"295":80,"296":44,"297":182,"298":1,"299":195,"300":108,"301":237,"302":213,"303":118,"304":15,"305":14,"306":255,"307":139,"308":32,"309":217,"310":16,"311":233,"312":27,"313":193,"314":15,"315":184,"316":222,"317":140,"318":2,"319":63,"320":210,"321":244,"322":23,"323":168,"324":133,"325":170,"326":139,"327":167,"328":41,"329":137,"330":208,"331":99,"332":109,"333":197,"334":2,"335":17,"336":198,"337":92,"338":58,"339":136,"340":138,"341":197,"342":81,"343":4,"344":32,"345":249,"346":175,"347":252,"348":17,"349":19,"350":87,"351":188,"352":166,"353":214,"354":127,"355":92,"356":37,"357":13,"358":240,"359":65,"360":245,"361":120,"362":184,"363":242,"364":237,"365":135,"366":241,"367":89,"368":102,"369":0,"370":9,"371":48,"372":6,"373":170,"374":27,"375":89,"376":53,"377":78,"378":172,"379":155,"380":224,"381":179,"382":30,"383":179}

**Comment by rozele** [comment] 2016-10-24 15:14
This looks a bit strange to me... In theory, the response object should be `[ [21], [1], [**[]**], 436]`, let me check the implementations for other platforms to see how they are handling this kind of response payload.

**Comment by rozele** [comment] 2016-10-24 15:21
The issue is definitely with the missing arguments list for the first method call, but the question is why the arguments list is "disappearing".

**Comment by Petter-W** [comment] 2016-10-27 10:40
@rozele It works if we convert the data from/to JSON before we feed it to our native module. (`var argument = JSON.parse(JSON.stringify(argument));`), but it's not optimal.

**Comment by rozele** [comment] 2016-10-27 14:11
@Petter-W yeah obviously that's not a good thing.  Have you tried stepping through the code to see where the value is "lost"?  Also, have you confirmed if this bug also occurs on Android or iOS?

**Comment by rozele** [comment] 2017-02-16 18:44
@Petter-W @henningms closing this issue for now, please try updating react-native and react-native-windows and confirm that this is not also a bug on Android.

**Closed by rozele** 2017-02-16 18:44 UTC
