### ISSUE TITLE
Code Push

### ISSUE THREAD

**Issue by andrewwebber** [ReactWindows/react-native-windows#702] opened 2016-09-16 18:17 UTC
I have not been able to get codepush working for windows. Android, iOS no problem

Microsoft/code-push#306

**Comment by rozele** [comment] 2016-09-17 09:30
@andrewwebber what version of react-native-windows? Also, may make sense to file an issue on http://github.com/Microsoft/react-native-code-push as well.

**Comment by rozele** [comment] 2016-09-17 09:31
Also @andrewwebber, we currently have no way to support the `react-native link` command, so there would need to be some manual changes to the native .sln and .csproj files for your project to get things working.  I think Code Push had documented this at some point.

**Comment by andrewwebber** [comment] 2016-09-19 16:21
@rozele naturally I have followed all of the documentation on code push for windows (including adding the additional windows code push solution project). I have been successful with the exact same app on iOS and Android however Windows hangs.

I have also filed a bug on code push to unfortunately no traction. I think code push for windows would be very useful for a lot of developers.

**Comment by rozele** [comment] 2016-09-19 17:00
@andrewwebber Indeed, it's something we definitely want to see working.  By not working, is it that the app is not compiling, or is there some other specific issue?

**Comment by andrewwebber** [comment] 2016-09-19 17:32
@rozele 

When an update is detected is seems to hang when trying to boot the new bundle and as the loading time is so long I think windows aborts the app starting. It is possible to get into a state where after an update has been restarted that a rollback does not take place

```javascript
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import codePush from "react-native-code-push";

class examplepush extends Component {
  constructor(){
    super();
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.windows.js
        </Text>
        <Text style={styles.instructions}>
          Press Ctrl+R to reload,{'\n'}
          Shift+F10 or shake for dev menu
        </Text>
        <Text>Version 1.0.15</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

let codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_RESUME };
App = codePush(codePushOptions)(examplepush)

AppRegistry.registerComponent('examplepush', () => App);
```

**Comment by rozele** [comment] 2016-09-23 15:28
Ah, thanks for the clarification @andrewwebber.  I think this is related to issues with blocking calls along the Dispose path for ReactContext.  I hadn't invested much time in removing those blocking calls, because I was (incorrectly) assuming they were Debug / Dev only (live reloading, etc.).  Of course, it's a public surface, and is being used to reload for CodePush.  Anyway, I'll put up a PR shortly to remove those blocking calls.

**Comment by andrewwebber** [comment] 2016-09-27 10:30
@rozele is there a build that one can test or does one just wait for the next release of react-native-windows

**Comment by rozele** [comment] 2016-09-27 15:10
@andrewwebber I'm going to get this into 0.33 and 0.34 later today.

**Comment by andrewwebber** [comment] 2016-09-29 17:06
@rozele after testing 0.34 this did not get code push working. App launches and then hangs.

Additional logs from event viewer
....
Package 4966a94d-8ca8-4bd6-9c4c-52911164eef9_1.0.0.0_x64__0cn3bep7b0bkm+App was terminated because it took too long to suspend.
.........
Faulting application name: examplepush3.exe, version: 1.0.0.0, time stamp: 0x57ed485c
Faulting module name: SharedLibrary.dll, version: 1.4.24201.0, time stamp: 0x574e6cd1
Exception code: 0x00001007
Fault offset: 0x000000000041cf48
Faulting process ID: 0x27f4
Faulting application start time: 0x01d21a7391c5a799
Faulting application path: C:\projects\examplepush3\windows\examplepush3\bin\x64\ReleaseBundle\AppX\examplepush3.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.1.3_1.3.24201.0_x64__8wekyb3d8bbwe\SharedLibrary.dll
Report ID: 380822cf-5e43-4bd1-902a-75ba7f74193d
Faulting package full name: 4966a94d-8ca8-4bd6-9c4c-52911164eef9_1.0.0.0_x64__0cn3bep7b0bkm
Faulting package-relative application ID: App

**Comment by rozele** [comment] 2016-10-03 18:05
@andrewwebber I'll take another look

**Comment by rozele** [comment] 2016-10-03 21:42
@andrewebber if you debug from Visual Studio and pause the app when it's hanging, open the "Threads" dialog, do you see a thread hanging on "RollbackUpdate"?

**Comment by rozele** [comment] 2016-10-04 14:25
@andrewwebber just so I'm sure I have the repro, the issue is that when you run the app the first time an update is available, it downloads the update and says something like "update will be applied next time app restarts".  Then, when you restart the app, the app hangs indefinitely (until crashing) and you get a message like "Update did not finish loading the last time, rolling back to a previous version."

**Comment by rozele** [comment] 2016-10-04 15:21
@andrewwebber I think I solved the problem for update on restart with this:
https://github.com/Microsoft/react-native-code-push/pull/545

Taking a look at update on resume now.

**Comment by rozele** [comment] 2016-10-11 02:59
Closing, all CodePush issues should be resolved.

**Closed by rozele** 2016-10-11 02:59 UTC
Labels: in progress
