### ISSUE TITLE
UIExplorer - Missing back-icon.png

### ISSUE THREAD

**Issue by joewood** [ReactWindows/react-native-windows#714] opened 2016-09-25 15:56 UTC
After cloning, installing and running app returns the following error when selecting the ExperimentalNavigator tab example:
```
Requiring unknown module "./assets/back-icon.png". If you sure the module is there, try restarting the packager or running "npm install".
```

Looks like the file is being imported here: https://github.com/facebook/react-native/blob/fc864a22bd00464c4219c6ddb6aa3d923aeb26dc/Libraries/CustomComponents/NavigationExperimental/NavigationHeaderBackButton.js

The assets directory doesn't have any default or windows PNG files:
https://github.com/facebook/react-native/tree/fc864a22bd00464c4219c6ddb6aa3d923aeb26dc/Libraries/CustomComponents/NavigationExperimental/assets

**Comment by joewood** [comment] 2016-09-25 16:06
I guess this is tricky to solve. Either the core react-native should have a default *platform agnostic* asset in that directory, or the UI Example for Windows needs to provide a custom renderer with its own `NavigationalBackButton`.

**Comment by rozele** [comment] 2016-09-26 13:25
This is a dupe of #223, I have a fix, but there was another issue related to CSSLayout that also needs to be resolved.

**Closed** 2016-09-26 13:26 UTC
Labels: duplicate

**Comment by rozele** [comment] 2016-09-26 17:33
This should be resolved now.  However, there is another issue related to the matrix transform animation used by NavigationExperimental.  For some reason, when the header title is animated away during a push route operation, it's "clickable" area does not follow it, and it is covering the back button...
